#import "../template.typ": *

= Lecture 16

== Electromagnetic and Electrostatic Thruster Thrust

The thrust of a HET or GIT or any electric thruster which accelerates ions using a potential difference is given by the expression shown in *@16-electric-thrust*.

$
  T = accent(m, dot)c approx accent(m, dot)_i v_i
$<16-electric-thrust>

Where $accent(m, dot)_i$ is the mass flow rate of the ions and $v_i$ is the velocity of the ions. The mass flow rate of
the ions can be calculated using *@16-ion-flow-rate*.

$
  accent(m, dot)_i = (I_b M_"ion")/(q)
$<16-ion-flow-rate>

Where $I_b$ is the ion beam current. Finally a full expression for the thrust can be generated by substituting *@16-ion-flow-rate* and *@15-perp-vel* into *@16-electric-thrust*, yielding *@16-electric-thrust-2*.

$
  T = sqrt((2 M_"ion")/e) I_b sqrt(V_b)
$<16-electric-thrust-2>

Often Xenon is used as the propellant, meaning the equation can be simplified as many of the parameters are known, this simplified expression is shown in *@16-electric-thrust-simple*.

$
  T = 1.651 I_b sqrt(V_b) quad quad [m N]
$<16-electric-thrust-simple>

Note that the input power can be calculated as $P_(i n) = I_b V_b$.

=== Efficiency Parameters

*@16-electric-thrust-simple* assumes that the thruster is 100% efficient, there are a few efficiency parameters which can be applied to make the equations more realistic, the first parameter for the beam divergence is shown in *@16-beam-divergence*.

$
  eta_(c o s) = 1/2(1 + cos^2(theta))
$<16-beam-divergence>

Where theta is []. The second parameter is the loss in efficiency due to ions which have been doubly ionized, this is shown in *@16-double-charge*.

$
  alpha = (1 + 1/sqrt(2) I^(+ +)/I^+)/(1 + I^(+ +)/I^+)
$<16-double-charge>

== Electromagnetic and Electrostatic Real Thruster Thrust

The actual thrust produced by a GIT or HET is given by substituting *@16-beam-divergence* and *@16-double-charge* into *@16-electric-thrust*, yielding *@16-real-thrust-electrostatic*.

$
  T = alpha eta_(c o s) sqrt((2 M_"ion")/e) I_b sqrt(V_b) quad --> quad T = alpha eta_(c o s) 1.651 I_b sqrt(V_b) quad quad [m N]
$<16-real-thrust-electrostatic>

== Electromagnetic and Electrostatic Thruster $I_(s p)$ and Efficiency Terms

The efficiency of a HET or GIT or any electric thruster which accelerates ions using a potential difference is given by *@16-ideal-electric-isp*, note that *@15-perp-vel* has been substituted in.

$
  I_(s p) = c/g_0 approx v_i/g_0 = 1/g_0 sqrt((2 q V_b )/M_"ion")
$<16-ideal-electric-isp>

Similar to the thrust, there exists efficiency parameters. The real $I_(s p)$ equation makes use of the same parameters with the addition of the thruster mass utilization efficiency which is a measure of how much of the propellant is ionized, this is shown in *@16-mass-utilization*.

$
  eta_m = accent(m, dot)_i / accent(m, dot) = I_b / q M_"ion"/accent(m, dot)
$<16-mass-utilization>

where $accent(m, dot)$ is the mass flow rate of the propellent. The real $I_(s p)$ with the efficiency applied is therefore shown in *@16-real-isp*.

$
  I_(s p) = (alpha eta_(c o s) eta_m)/g_0 sqrt((2 q V_b )/M_"ion") quad --> quad I_(s p) = 123.6 alpha eta_(c o s) eta_m sqrt(V_b)
$<16-real-isp>

== Electromagnetic and Electrostatic Thruster Efficiencies

Another useful efficiency parameter for ion accelerating thrusters is the electrical efficiency shown in *@16-elec-eff*.

$
  eta_e = (I_b V_b)/(I_b V_b + P_0)
$<16-elec-eff>

Where $P_0$ is the other power input to the thruster required to create the thrust beam such as but not limited to electrical cost of producing the ions, cathode heater or keeper power, grid currents. The total efficiency can be written in terms of all of the defined efficiencies shown in *@16-total-eff*.

$
  eta_(t h) = (1/2 accent(m, dot) c^2)/(P_(i n)) = (alpha eta_(c o s))^2 eta_e eta_m
$<16-total-eff>

Another useful efficiency parameter is the discharge loss shown in *@16-discharge-loss*. Note that this parameter is not technically as it has units of $W"/"A$.

$
  eta_d = P_d/I_b
$<16-discharge-loss>

An interesting property is shown if the discharge loss is plotted against the mass utilization efficiency, this plot is shown in *@16-etad-etam*. At higher propellent utilization efficiencies, the discharge loss increases, this is because at high $eta_m$s, there are less neutrals within the exhaust which have a passive effect of cooling the exhaust. This therefore means operating at high $eta_m$s leads to a high electron temperature increasing $eta_d$.

#figure(
  image("images/16-discharge-loss.png", width: 80%),
  caption: [Plot of discharge loss against mass utilization efficiency.],
  supplement: [Figure],
  kind: figure,
)<16-etad-etam>

== Difficulties in Estimating HET Performance

There are some key parameters that have been mentioned for calculating key performance metrics that are difficult or not possible to experimentally measure. One key parameter that is difficult to measure is the *coupling voltage* shown in *@16-vc* and *@16-vc-plot*.

#grid(
  columns: 2,
  [\ \ \ \  $
    V_C = V_"Plasma" + V_"Cathode"
    \
    V_C = V_d - V_b
    \ therefore
    V_b = V_d - V_C = V_d - (V_"Plasma" + V_"Cathode")
  $<16-vc>],
  [#figure(
    image("images/16-coupling-voltage.png", width: 80%),
    caption: [Plot of voltage applied across a HET],
    supplement: [Figure],
    kind: figure,
  )<16-vc-plot>],
)

$V_d$ can be experimentally measured however $V_"Plasma"$ cannot be measured $V_"Cathode"$, this means that a thrust stand must be used to calculate key performance parameters. Another key parameter that is cannot be measured is the *beam current* $I_b$, the equation including it is shown in *@16-discharge-current*.

$
  I_d = I_b + I_(e c)
$<16-discharge-current>

Simply measuring the anode current doesn't allow for calculation of $I_b$ as the backstreaming electron current $I_(e c)$ cannot be measured and the physics behind why this happens is still unknown. Another key efficiency parameter is the current discharge efficiency shown in *@16-current-discharge-eff*.

$
  eta_b = I_b / I_d
$<16-current-discharge-eff>

Which is a measure of how much $I_(e c)$ there is, a good thruster will keep $I_(e c)$ as low as possible. Another aspect to note is that the $P_(i n)$ and $accent(m, dot)$ terms in $eta_(t h)$ contain all of the contributions shown in *@16-advanced-total-efficiency*.

$
  accent(m, dot) = accent(m, dot)_"anode" + accent(m, dot)_"cathode" quad P_(i n) = P_"anode" + P_"cathode" + P_"electromagnets" quad P_"anode" = I_d V_d
  \
  eta_(t h) = (1/2 accent(m, dot) c^2)/(P_(i n))= (1/2 (accent(m, dot)_"anode" + accent(m, dot)) c^2)/(P_"anode" + P_"cathode" + P_"electromagnets") = (1/2 (accent(m, dot)_"anode" + accent(m, dot)) c^2)/(I_d V_d + P_"cathode" + P_"electromagnets")
$<16-advanced-total-efficiency>

One quick way of approximating the total efficiency when certain parameters cannot be accurately calculated is by utilizing the anode efficiency shown in *@16-anode-eff*.

$
  eta_"anode" = F^2/(2 accent(m, dot)_"anode" I_d V_d)
$<16-anode-eff>

== Closing Remarks on HETs

HETs stand out as the most dominant type of electric propulsion method used in space in the modern day, with their development being a key area of focus. They set poised for use in wider and wider mission requirements and sit in the goldilocks zone for space missions (good $I_(s p)$ and good thrust). There are some drawbacks and lack of understanding present, some key areas of development are:

- Smaller HETs see much lower total efficiencies.
- Larger HETs come with the penalty of much greater power requirements.
- Operating on different propellants without large performance loss.
- The specific mechanisms behind Bohm diffusion and why electrons fall back to the anode.
