#import "../template.typ": *

= Lecture 16

== Electromagnetic and Electrostatic Thruster Thrust

The thrust of a HET or GIT or any electric thruster which accelerates ions using a potential difference is given by the expression shown in *@16-electric-thrust*.

$
  T = accent(m, dot)c approx accent(m, dot)_i v_i
$<16-electric-thrust>

Where $accent(m, dot)_i$ is the mass flow rate of the ions and $v_i$ is the velocity of the ions. The mass flow rate of
the ions can be calculated using *@16-ion-flow-rate*.

$
  accent(m, dot)_i = (I_b M_"ion")/(q)
$<16-ion-flow-rate>

Where $I_b$ is the ion beam current. Finally a full expression for the thrust can be generated by substituting *@16-ion-flow-rate* and *@15-perp-vel* into *@16-electric-thrust*, yielding *@16-electric-thrust-2*.

$
  T = sqrt((2 M_"ion")/e) I_b sqrt(V_b)
$<16-electric-thrust-2>

Often Xenon is used as the propellant, meaning the equation can be simplified as many of the parameters are known, this simplified expression is shown in *@16-electric-thrust-simple*.

$
  T = 1.651 I_b sqrt(V_b) quad quad [m N]
$<16-electric-thrust-simple>

Note that the input power can be calculated as $P_(i n) = I_b V_b$.

=== Efficiency Parameters

*@16-electric-thrust-simple* assumes that the thruster is 100% efficient, there are a few efficiency parameters which can be applied to make the equations more realistic, the first parameter for the beam divergence is shown in *@16-beam-divergence*.

$
  eta_(c o s) = 1/2(1 + cos^2(theta))
$<16-beam-divergence>

Where theta is []. The second parameter is the loss in efficiency due to ions which have been doubly ionized, this is shown in *@16-double-charge*.

$
  alpha = (1 + 1/sqrt(2) I^(+ +)/I^+)/(1 + I^(+ +)/I^+)
$<16-double-charge>

== Electromagnetic and Electrostatic Real Thruster Thrust

The actual thrust produced by a GIT or HET is given by substituting *@16-beam-divergence* and *@16-double-charge* into *@16-electric-thrust*, yielding *@16-real-thrust-electrostatic*.

$
  T = alpha eta_(c o s) sqrt((2 M_"ion")/e) I_b sqrt(V_b) quad --> quad T = alpha eta_(c o s) 1.651 I_b sqrt(V_b) quad quad [m N]
$<16-real-thrust-electrostatic>

== Electromagnetic and Electrostatic Thruster $I_(s p)$ and Efficiency Terms

The efficiency of a HET or GIT or any electric thruster which accelerates ions using a potential difference is given by *@16-ideal-electric-isp*, note that *@15-perp-vel* has been substituted in.

$
  I_(s p) = c/g_0 approx v_i/g_0 = 1/g_0 sqrt((2 q V_b )/M_"ion")
$<16-ideal-electric-isp>

Similar to the thrust, there exists efficiency parameters. The real $I_(s p)$ equation makes use of the same parameters with the addition of the thruster mass utilization efficiency which is a measure of how much of the propellant is ionized, this is shown in *@16-mass-utilization*.

$
  eta_m = accent(m, dot)_i / accent(m, dot) = I_b / q M_"ion"/accent(m, dot)
$<16-mass-utilization>

where $accent(m, dot)$ is the mass flow rate of the propellent. The real $I_(s p)$ with the efficiency applied is therefore shown in *@16-real-isp*.

$
  I_(s p) = (alpha eta_(c o s) eta_m)/g_0 sqrt((2 q V_b )/M_"ion") quad --> quad I_(s p) = 123.6 alpha eta_(c o s) eta_m sqrt(V_b)
$<16-real-isp>

== Electromagnetic and Electrostatic Thruster Efficiencies

Another useful efficiency parameter for ion accelerating thrusters is the electrical efficiency shown in *@16-elec-eff*.

$
  eta_e = (I_b V_b)/(I_b V_b + P_0)
$<16-elec-eff>

Where $P_0$ is the other power input to the thruster required to create the thrust beam such as but not limited to electrical cost of producing the ions, cathode heater or keeper power, grid currents. The total efficiency can be written in terms of all of the defined efficiencies shown in *@16-total-eff*.

$
  eta_(t h) = (1/2 accent(m, dot) c^2)/(P_(i n)) = (alpha eta_(c o s))^2 eta_e eta_m
$<16-total-eff>

Another useful efficiency parameter is the discharge loss shown in *@16-discharge-loss*. Note that this parameter is not technically as it has units of $W"/"A$.

$
  eta_d = P_d/I_b
$<16-discharge-loss>

An interesting property is shown if the discharge loss is plotted against the mass utilization efficiency, this plot is shown in *@16-etad-etam*. At higher propellent utilization efficiencies, the discharge loss increases, this is because at high $eta_m$s, there are less neutrals within the exhaust which have a passive effect of cooling the exhaust. This therefore means operating at high $eta_m$s leads to a high electron temperature increasing $eta_d$.

#figure(
  image("images/16-discharge-loss.png", width: 80%),
  caption: [Plot of discharge loss against mass utilization efficiency.],
  supplement: [Figure],
  kind: figure,
)<16-etad-etam>

== Difficulties in Estimating HET Performance

There are some key parameters that have been mentioned for calculating key performance metrics that are difficult or not possible to experimentally measure. One key parameter that is difficult to measure is the *coupling voltage* shown in *@16-vc* and *@16-vc-plot*.

#grid(
  columns: 2,
  [\ \ \ \  $
    V_C = V_"Plasma" + V_"Cathode"
    \
    V_C = V_d - V_b
    \ therefore
    V_b = V_d - V_C = V_d - (V_"Plasma" + V_"Cathode")
  $<16-vc>],
  [#figure(
    image("images/16-coupling-voltage.png", width: 80%),
    caption: [Plot of voltage applied across a HET],
    supplement: [Figure],
    kind: figure,
  )<16-vc-plot>],
)

$V_d$ can be experimentally measured however $V_"Plasma"$ cannot be measured $V_"Cathode"$, this means that a thrust stand must be used to calculate key performance parameters. Another key parameter that is cannot be measured is the *beam current* $I_b$, the equation including it is shown in *@16-discharge-current*.

$
  I_d = I_b + I_(e c)
$<16-discharge-current>

Simply measuring the anode current doesn't allow for calculation of $I_b$ as the backstreaming electron current $I_(e c)$ cannot be measured and the physics behind why this happens is still unknown. Another key efficiency parameter is the current discharge efficiency shown in *@16-current-discharge-eff*.

$
  eta_b = I_b / I_d
$<16-current-discharge-eff>

Which is a measure of how much $I_(e c)$ there is, a good thruster will keep $I_(e c)$ as low as possible. Another aspect to note is that the $P_(i n)$ and $accent(m, dot)$ terms in $eta_(t h)$ contain all of the contributions shown in *@16-advanced-total-efficiency*.

$
  accent(m, dot) = accent(m, dot)_"anode" + accent(m, dot)_"cathode" quad P_(i n) = P_"anode" + P_"cathode" + P_"electromagnets" quad P_"anode" = I_d V_d
  \
  eta_(t h) = (1/2 accent(m, dot) c^2)/(P_(i n))= (1/2 (accent(m, dot)_"anode" + accent(m, dot)) c^2)/(P_"anode" + P_"cathode" + P_"electromagnets") = (1/2 (accent(m, dot)_"anode" + accent(m, dot)) c^2)/(I_d V_d + P_"cathode" + P_"electromagnets")
$<16-advanced-total-efficiency>

One quick way of approximating the total efficiency when certain parameters cannot be accurately calculated is by utilizing the anode efficiency shown in *@16-anode-eff*.

$
  eta_"anode" = F^2/(2 accent(m, dot)_"anode" I_d V_d)
$<16-anode-eff>

== Closing Remarks on HETs

HETs stand out as the most dominant type of electric propulsion method used in space in the modern day, with their development being a key area of focus. They set poised for use in wider and wider mission requirements and sit in the goldilocks zone for space missions (good $I_(s p)$ and good thrust). There are some drawbacks and lack of understanding present, some key areas of development are:

- Smaller HETs see much lower total efficiencies.
- Larger HETs come with the penalty of much greater power requirements.
- Operating on different propellants without large performance loss.
- The specific mechanisms behind Bohm diffusion and why electrons fall back to the anode.

It is also important that the domination of Hall thrusters in the EP sector mean that R&D is taken away from other forms of EP.

== Magnetoplasmadynamic (MPD) Thrusters

These thrusters utilize both an electric field and an induced magnetic field to ionize and accelerate propellent. An image of such a thruster is shown in *@16-mpd*.

#figure(
  image("images/16-mpd.png", width: 69%),
  caption: [Image of the anatomy of a MPD thruster.],
  supplement: [Figure],
  kind: figure,
)<16-mpd>

Note that an MPD is very similar to an arcjet, the main difference is the size of teh current applied. MPDs feature much higher currents which produce a self field which is not true in arcjets. MPD thrusters generate thrust through the following mechanism:

- A very large current is applied between the anode and cathode ($10-100 k A$).
- The applied voltage between the anode and cathode cause the propellent which is fed into the annular chanel to break down into a plasma.
- The high plasma current generates a strong magnetic field, and the resulting Lorentz force ($F = J times B$) electromagnetically accelerates the plasma along and out of the channel, producing thrust.

There exists two types of MPD, these are *self field* where the magnetic field is solely generated via the high current flow and *applied field* which generate a magnetic field using a solenoid magnet to create the magnetic field. A cross sectional image showing these two types is seen in  *@16-mpd-self-applied*.

#figure(
  image("images/16-mpd-self-applied.png", width: 80%),
  caption: [Image of a self field MPD vs an applied field MPD. ],
  supplement: [Figure],
  kind: figure,
)<16-mpd-self-applied>

MPDs can achieve high efficiencies and high thrusts but require an incredibly high power draw. A comparison between MPDs ion thrusters and Hall effect thrusters is shown in *@16-mpd-comparison*.

#figure(
  table(
    columns: 5,
    fill: (col, row) => if row == 0 { gray } else { white },
    align: center + horizon,
    table.header[*Type*,][*Thrust Range (mN)*][*Isp Range (s)*][*Thruster Efficiency*][*Input Power Range (W)*],

    [MPD], [0.001 - 20,000], [2000 - 5000+], [30 - 50], [2000 - 100,000+],
    [Ion Thruster], [0.01 - 500], [1500 - 8000], [60 - 80], [400 - 4300],
    [Hall Thruster], [0.01 - 2000], [1500 - 2000], [30 - 50], [1000 - 4500],
  ),
  caption: [MPD vs HET vs GIT performance.],
)<16-mpd-comparison>

MPDs do have some issues however, which limits their widespread use, these are:

- Require very high power inputs to achieve high thrust and efficiencies.
  Electrode erosion.
- Very large electrical components.
- Low efficiencies result in huge heat losses.
- 'Onset' phenomena where instabilities occur at higher currents.

== Pulsed Plasma Thrusters

These are a simpler form of electromagnetic thruster in comparison to a HET or an MPD, an image of such a system is shown in *@16-ppt*.

#figure(
  image("images/16-ppt.png", width: 60%),
  caption: [Schematic image of a PPT.],
  supplement: [Figure],
  kind: figure,
)<16-ppt>

PPTs produce thrust through the following mechanism:

- The spark plug ablates a thin layer of the propellent block (Usually made of Teflon or PTFE).
- The partially ionized ablated propellent flows between the two channels where a large current is applied.
- The large current further ionizes the propellent as well as producing a strong self magnetic field.
- The ionizes plasma is then accelerated through the channel through electromagnetic acceleration ($F = J times B$).

Due to their simplicity and low voltage requirements, PPTs have very low thrusts and efficiencies. A comparison of PPT performance is shown in *@16-ppt-comparison*

#figure(
  table(
    columns: 5,
    fill: (col, row) => if row == 0 { gray } else { white },
    align: center + horizon,
    table.header[*Type*,][*Thrust Range (mN)*][*Isp Range (s)*][*Thruster Efficiency*][*Input Power Range (W)*],

    [Resistojet], [200 - 300], [200 - 350], [65 - 90], [50 - 500],
    [PPT], [0.05 - 10], [600 - 2000], [10], [10 - 100],
    [MPD thruster], [0.001 - 20,000], [2000 - 5000], [30 - 50], [2000 - 100,000],
  ),
  caption: [PPT performance.],
)<16-ppt-comparison>

#pagebreak()

#lecture("Into to Electrostatic Propulsion", 2, 9)

Electrostatic thrusters accelerate electrons solely through an electric field, driven by a potential difference. The types of electrostatic thrusters covered in this section are:

- Gridded Ion Thrusters (GIT)
  - Radiofrequency Ion Thruster (RIT)
  - Microwave Ion Thruster
  - Electron Bombardment Ion Thruster (AKA Kaufman Ion Thruster)
- Electrospray / FEEP thruster

== Radiofrequency Ion Thruster

In this type of ion thruster, the electrons are imparted energy via a radio frequency coil wrapped around the discharge chamber. A schematic diagram of such a thruster is shown in *@16-rit*.

#figure(
  image("images/16-RIT.png", width: 80%),
  caption: [Schematic image of a RIT.],
  supplement: [Figure],
  kind: figure,
)<16-rit>

In a RIT a plasma is produced via the following mechanism:


- An alternating current in the RF coil (frequency $approx$ 1 - 30 MHz) induces an *axial time varying magnetic field* in the discharge chamber.
- Due to Faraday's law, this changing magnetic field induces *an azimuthal electric field* in the discharge chamber.
- This induced electric field acts on the electrons, causing them to oscillate azimuthally with collisions converting the oscillatory motion into thermal energy through ohmic heating.
- Hot electrons collide with neutrals ionizing them and increasing plasma density.
- When the RF polarity is reversed, the direction of the electron movement is reversed which means the net effect on the electrons is heating not drift.

An expression for the induced axial magnetic field can be derived and is shown in *@16-Bz*

$
  B_Z = (N I)/(mu_0) e^(i omega t)
$<16-Bz>

Where:

- *$B_Z$*: Strength of the axial magnetic field ($T$).
- *$N$*: Number of coils in the RF coil.
- *$I$*: The current flow through the RF coil ($A$).
- *$mu_0$*: The permeability of the vacuum = $4pi times 10^(-7) H "/"m$
- *$t$*: Time (s)

Utilizing Faraday's law and rearranging the resulting expression, an equation for the azimuthal electric field can be derived, this is shown in *@16-Etheta*.

$
  nabla times accent(E, ->) = -(partial accent(B, ->))/(partial t) quad --> quad E_theta = - (i omega r)/2 B_Z_0 e^(i omega t)
$<16-Etheta>

Where $r$ is the radius of the discharge chamber and $B_Z_0$ is the initial axial magnetic field.

== Microwave Ion Thrusters

Also known as electron cyclotron resonance ion thrusters, this type of thruster uses some of the same principles as a RIT but with the added benefit of cyclotron resonance. A schematic image of such a thruster is shown in *@16-mit*.

#figure(
  image("images/16-MIT.png", width: 30%),
  caption: [Schematic image of a Microwave Ion Thruster.],
  supplement: [Figure],
  kind: figure,
)<16-mit>

Microwave ion thrusters generate a plasma through the following mechanism:

- A microwave antenna injects microwaves (frequency $approx$ 2.4 - 2.8 GHz) into the discharge chamber.
- As microwaves are an EM wave, an alternating magnetic and electric field are introduced.
- The azimuthal electric field causing ohmic heating of the electrons in the same manner as a RIT just at a much higher frequency.
- Due to a static magnetic field which produces a $B$ at a specific value corresponding to the Lamor radius, the electrons undergo Electron Cyclotron Resonance (ECR).
- ECR means that:
  - Electrons absorb energy very efficiently meaning low power plasma ignition.
  - Plasma production is much easier meaning high plasma density.
  - No internal electrodes needed.
  - Longer lifetime and excellent efficiencies.

== Electron Bombardment Ion Thruster

This type of ion thruster utilizes a different mechanism to the RIT to generate a plasma. A schematic diagram showing an example of an electron bombardment ion thruster is shown in *@16-electron-bombardment*.

#figure(
  image("images/16-electron-bombardment.png", width: 60%),
  caption: [Schematic image of an electron bombardment ion thruster.],
  supplement: [Figure],
  kind: figure,
)<16-electron-bombardment>

Electron bombardment ion thrusters generate a plasma utilizing the following mechanism:

- A hollow cathode (electron gun) uses a small amount of propellent to introduce hot electrons into the discharge chamber.
- These electrons then ionize neutrals forming a plasma.
- As the ions accelerate out of the discharge chamber there develops a build up of electrons, therefore an anode is required on the walls to remove electrons.
- As the electrons are very mobile they quickly get attracted to teh anode and the potential is lost, to combat this a magnetic field is used to impeded the motion of teh electrons as they approach teh anode.

== Ion Thruster Grids

All of the types of ion thrusters mentioned require grids to accelerate the ions within the plasma. Typically GITs consist of three grids, these are:

- *Screen Grid*: Has a very high positive potential ($approx +1000V$). The plasma sits on the left side of the screen grid meaning that electrons are attracted to it forming a sheath ($w i d t h = lambda_D$). This sheath occludes the effect of the high positive potential to teh rest of the plasma.

- *Accelerator Grid*: This grid sits at a negative potential ($approx -200V - -500V$) and accelerates the ions forward when they enter the region between the screen grid and the accelerator grid.

- *Decelerator Grid*: This grid sits at a neutral charge in order to repel or decelerate backflowing positively charged plume ions which would have otherwise collided with the accelerator grid and eroded it.

#pagebreak()
