#import "../template.typ": *

#lecture("Lecture 15", 1, 8)

== Calculating Larmor Radii in HETs

For a HET, the ions should have a large Larmor radius so they are not bent out of shape and stay straight and the electrons should have a small Larmor radius so they stay within the confinement zone. To calculate the radii, *@14-larmor-radius* can be used in combination with the equations defined in *@15-perp-vel*.

$
  v_(perp)_"electron" = v_(t h) = sqrt((8 k T_e)/(pi m_e))
  quad quad
  v_(perp)_"ion" = v_i = sqrt((2 q V_b)/(m_i))
$<15-perp-vel>

Where the first equation is the thermal velocity as this is dominating for the electrons and the second is the energy gained due to the electrostatic attraction. Note that $m_i$ is the ion mass and $V_b$ is teh beam voltage.

== Hall Effect

The Hall effect itself is the *perpendicular potential difference experienced as a charged particle moves through a magnetic field*. Hall effect thrusters use this to confine the electrons within the magnetic field at the mouth of the thruster. These electrons can be thought of as a current (a Hall current). Therefore due to the Hall effect, a potential difference is created which counteracts the upstream potential difference, keeping the electrons in place and causing them to act as a pseudo-grid. The drift velocity of an electron can be calculated using the equation shown in *@15-drift-velocity*.

$
  accent(v, ->)_(E times B) = (accent(E, ->) times accent(B, ->))/accent(B, ->)^2
  quad --> quad v_(E times B) = E_z / B_r
$<15-drift-velocity>

Where the first equation is the general vector form and the second equation is a simplified form taking into account teh geometry of the Hall thruster. $E_z$ is the axial electric field and $B_r$ is the radial magnetic field. The Hall current which is the azimuthal current generated by the stream of electrons can be calculated using *@15-hall-current*.

$
  I_H = n_e e (integral_0^L v_(E times B) d z)w = n_e e (integral_0^L E_z / B_r d z)w approx n_e e w V_d/B
$<15-hall-current>

Where:

- *$n_e$*: Electron density (electrons / $m^3$)
- *$e$*: Electron charge $= 1.6 times 10^(- 19) C$
- *$w$*: Annular channel width ($m$)
- *$L$*: Length of Hall current in the channel ($m$).
- *$V_d$*: Discharge voltage ($V_d$).

Note that $V_d/B approx 1$ meaning that the hall current is mostly driven by the electron density and annular width.

#pagebreak()
