#import "../template.typ": *

#lecture("Lecture 21", 1, 11)

== Solar Sails

Solar sails do not use a mass driver, instead they generate thrust through the momentum change of photons. Each photon imparts an almost negligible amount of momentum ($approx 1.326 times 10^(-27) m k g "/" s$ per photon) and so solar sailing spacecraft must:

- Maximize the area of the sail to increase the number of incident photons.
- Must be incredibly light to maximize tha acceleration.

As there is no need for propellent and engines there can be a significant mass reduction, particularly for high $Delta V$ missions. Solar sails can also use an orientation strategy called tacking in order to vary its orbit, shown in *@21-tacking*.

#figure(
  image("images/21-solar-sailing.png", width: 58%),
  caption: [A solar sailing spacecraft's trajectory using tacking.],
  supplement: [Figure],
  kind: figure,
)<21-tacking>

== Solar Sail Performance

The momentum of a given photon can be calculated by substituting the mass energy equivalence equation into the momentum equation, yielding *@21-photon-momentum*. The resulting momentum change is also shown in *@21-photon-momentum*.

$
  E = m c^2 quad quad p = m c quad --> quad p = (E/c^2)c = E/c \
  Delta p = (Delta E)/c
$<21-photon-momentum>

The change of energy can also be written in the form shown in *@21-incident-energy* where $A$ is the area, $W$ is the energy flux and $Delta t$ is the change in time.

$
  Delta E = W A Delta t
$<21-incident-energy>

An expression for the pressure exerted on the surface due to the photons can also be derived and is shown in *@21-photon-pressure*.

$
  P = 1/A ((Delta p)/(Delta t))
$<21-photon-pressure>

A final equation for solar pressure can be developed by substituting *@21-incident-energy* into *@21-photon-momentum* and then the resulting expression into *@21-photon-pressure*, this yields *@21-final-photon-pressure*.

$
  Delta p = (Delta E)/c = (W A Delta t)/c quad --> quad P = 1/A ((Delta p)/(Delta t)) = 1/A ((W A Delta t)/(c Delta t)) \
  therefore P = W/c
$<21-final-photon-pressure>

To find the thrust generated by a solar sail, *@21-final-photon-pressure* can be multiplied by the area, this final expression is shown in *@21-solar-sail-thrust*.

$
  F = P A = (W A)/c
$<21-solar-sail-thrust>

However, *@21-solar-sail-thrust* is an idealized equation, in reality there are losses due to wrinkles, absorption and the angle of incidence, these are included in the final corrected expression shown in *@21-solar-sail-corrected-thrust*.

#grid(
  columns: 2,
  column-gutter: 1cm,
  [#figure(
    image("images/21-alpha-definition.png", width: 58%),
    caption: [The definition for the angle of incidence of a solar sail],
    supplement: [Figure],
    kind: figure,
  )<21-alpha-definition>],

  [$ F = eta (W A)/c cos^2(alpha) $<21-solar-sail-corrected-thrust>

    Where:

    - *$F$*: Thrust (N).
    - *$eta$*: Sail coefficient $approx 1.8$.
    - *$W$*: Solar radiation flux ($W "/" m^2$).
    - *$A$*: Area ($m^2$)
    - *$c$*: Speed of light $approx 3 times 10^8 m"/"s$
    - *$alpha$*: Angle of incidence.
  ],
)

A useful parameter when referring to solar sails is the *sail loading*, it is defined in *@21-sail-loading*, Where $M_(s s)$ is the solar sail mass.

$
  sigma = M_(s s) / A
$<21-sail-loading>

== Issues with Solar Sails

Solar sails cannot be used below 800km, due to their very high drag. They also cannot be used beyond 0.25 AU as the solar flux is too weak. They also present complex orbital mechanics issues and attitude control issues. Furthermore there exists a complex issue of folding up and deploying the whole structure.

== Solar Sail $I_(s p)$

A rough expression can be developed for the $I_(s p)$ of a solar sail, this expression is shown in *@21-solar-sail-isp*.

$
  I_(s p) = (a_0 T)/(g_0 ln(M_0/M_f))
$<21-solar-sail-isp>

Where $a_0$ is the spacecraft acceleration (thrust / total spacecraft mass) and $T$ is the mission duration. The final mass $M_f$ assumed the weight of the solar sail is removed. The $I_(s p)$ for various different accelerations is shown plotted against chemical and electrical propulsion methods in *@21-solar-sail-isp-plotted*.

#figure(
  image("images/21-solar-sail-isp.png", width: 58%),
  caption: [The $I_(s p)$ of a solar sail compared with chemical and electric propulsion methods.],
  supplement: [Figure],
  kind: figure,
)<21-solar-sail-isp-plotted>

Note that in *@21-solar-sail-isp-plotted* the $I_(s p)$ of solar sails far exceeds traditional propulsion types as the mission duration increases.

== Solar Sail Geometries

There exist three main solar sail geometries, these are shown in *@21-solar-sail-types*, and explained in the bullet points below.

#figure(
  image("images/21-solar-sail-types.png", width: 65%),
  caption: [Types of solar sails.],
  supplement: [Figure],
  kind: figure,
)<21-solar-sail-types>

- *Square Sail*: Booms extend out from the spacecraft body and a rectangular sail unfurls.
- *Spinning Disk Sail*: The spacecraft spins and the solar sail expands out due to centrifugal force.
- *Heliogyro*: Rolls of sail extend out, these could then be angled to spin the spacecraft like a helicopter.

== Solar Sail Orbits and Further Uses of Solar Sails

Solar sails can fly in non-Keplerian orbits (spiral orbits, halo orbits). Solar sails are well suited to long interplanetary missions, reducing transit times to days.

Solar sails have been used for attitude control as well as to shine light onto the Earth. Interstellar microsailing exists as a possible method for interplanetary transport using lasers to accelerate a solar sail up to interplanetary speeds.

== Electric Sails

Instead of using the Sun's photons to impart momentum, electric sails use the Solar Wind which consists of charged particles moving very quickly. If a spacecraft has the opposite charge then it will be repelled by the solar wind and the sail would not need to be a full sail but tendrils instead.

#pagebreak()
